name: RUN flask_car24

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code 
              uses: actions/checkout@v4 

            - name: Setup Python 3.12.3 
              uses: actions/setup-python@v2 
              with:
                  python-version: 3.12.3
            
            - name: Install dependencies 
              working-directory: flask
              run: |
                  python3 -m pip install --upgrade pip
                  pip3 install -r requirements.txt
            
            - name: Run tests
              working-directory: flask
              run: |
                  pytest -s -v -p no:warnings test/